### TEST ENDPOINT mail/file, TASK 3

### Send email with a file attachment
POST http://localhost:6969/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/Ilya_G_Resume.pdf"
Content-Type: application/pdf

< ./src/Ilya_G_Resume.pdf
------CustomBoundary12345
Content-Disposition: form-data; name="emails"

elonmusk@x.com,jeffbezos@amazon.com,zuckerberg@meta.com
------CustomBoundary12345--


### Send email with file attachment and basic auth to one receiver
POST http://localhost:6969/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/Ilya_G_Resume.pdf"
Content-Type: application/pdf

< ./src/Ilya_G_Resume.pdf
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: text/plain

2004gusak@gmail.com
------CustomBoundary12345--


### Send email with file attachment and basic auth to multiple receivers
POST http://localhost:6969/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/Ilya_G_Resume.pdf"
Content-Type: application/pdf

< ./src/Ilya_G_Resume.pdf
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: text/plain

ilya.gusak.2016@mail.ru,2004gusak@gmail.com
------CustomBoundary12345--


### Send email with unsupported file attachment and basic auth
POST http://localhost:6969/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/logo.png"
Content-Type: image/png

< ./src/logo.png
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: text/plain

elonmusk@x.com
jeffbezos@amazon.com
zuckerberg@meta.com
------CustomBoundary12345--

### Send email with file attachment and unsupported receiver emails and basic auth
POST http://localhost:6969/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/Ilya_G_Resume.pdf"
Content-Type: application/pdf

< ./src/Ilya_G_Resume.pdf
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./src/document.docx
------CustomBoundary12345--




### ON Render.com TEST ENDPOINT mail/file, TASK 3

### Send email with a file attachment
POST https://doodocs-days-backend.onrender.com/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/Ilya_G_Resume.pdf"
Content-Type: application/pdf

< ./src/Ilya_G_Resume.pdf
------CustomBoundary12345
Content-Disposition: form-data; name="emails"

elonmusk@x.com,jeffbezos@amazon.com,zuckerberg@meta.com
------CustomBoundary12345--


### Send email with file attachment and basic auth to one receiver
POST https://doodocs-days-backend.onrender.com/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/Ilya_G_Resume.pdf"
Content-Type: application/pdf

< ./src/Ilya_G_Resume.pdf
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: text/plain

2004gusak@gmail.com
------CustomBoundary12345--


### Send email with file attachment and basic auth to multiple receivers
POST https://doodocs-days-backend.onrender.com/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/Ilya_G_Resume.pdf"
Content-Type: application/pdf

< ./src/Ilya_G_Resume.pdf
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: text/plain

ilya.gusak.2016@mail.ru,2004gusak@gmail.com
------CustomBoundary12345--


### Send email with unsupported file attachment and basic auth
POST https://doodocs-days-backend.onrender.com/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/logo.png"
Content-Type: image/png

< ./src/logo.png
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: text/plain

elonmusk@x.com
jeffbezos@amazon.com
zuckerberg@meta.com
------CustomBoundary12345--

### Send email with file attachment and unsupported receiver emails and basic auth
POST https://doodocs-days-backend.onrender.com/api/mail/file
Content-Type: multipart/form-data; boundary=----CustomBoundary12345
Authorization: Basic YWRtaW46cGFzc3dvcmQy

------CustomBoundary12345
Content-Disposition: form-data; name="file"; filename="./src/document.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./src/document.docx
------CustomBoundary12345
Content-Disposition: form-data; name="emails"; filename="emails.txt"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./src/document.docx
------CustomBoundary12345--